export const baseUrl = 'https://5950-2402-800-613e-1be0-309a-e0da-4682-2bf8.ngrok-free.app/';
const API = {
  baseUrl: baseUrl,
  register: () => baseUrl + 'api/auth/register',
  login: () => baseUrl + 'api/auth/login',
  logout: () => baseUrl + 'api/logout',
  getCategories: () => baseUrl + 'api/categories',
  getProducts: id => baseUrl + `api/products/${id}`,
  getProductDetail: id => baseUrl + `api/products_detail/${id}`,
  getProductsPopular: () => baseUrl + 'api/products_popular',
  getProductsSelling: () => baseUrl + 'api/products_selling',
  getProductsAll: () => baseUrl + 'api/products',
  getProductsFilter: (min_price,max_price,category_id) => baseUrl + `api/products_filter?min_price=${min_price}&max_price=${max_price}&category_id=${category_id}`,
  addToCart: () => baseUrl + 'api/cart/add_to_cart',
  deleteItemCart: (customer_id,product_id) => baseUrl + `api/cart/delete_item_cart?customer_id=${customer_id}&product_id=${product_id}`,
  cart: (id) => baseUrl + `api/cart/${id}`,
  increase: (id) => baseUrl + `api/cart/increase/${id}`,
  reduce: (id) => baseUrl + `api/cart/reduce/${id}`,
  addToFavorite: () => baseUrl + 'api/favorite/add_to_favorite',
  getFavorite: (id) => baseUrl + `api/favorite/${id}`,
  deleteItemFavorite: (customer_id,product_id) => baseUrl + `api/cart/delete_item_favorite?customer_id=${customer_id}&product_id=${product_id}`,
  addAddress: () => baseUrl + 'api/address/add_new_address',
  getAddress: (id) => baseUrl + `api/address/${id}`,
  getUpdateAddress: (id) => baseUrl + `api/address_update/${id}`,
  updateAddress: () => baseUrl + 'api/address/update_address',
  getBill: (id) => baseUrl + `api/order/get_bill/${id}`,
  placeOrder:() => baseUrl + 'api/order/place_order',
  getOrders: (id) => baseUrl + `api/order/list/${id}`,
  getOrderDetail: (order_id) => baseUrl + `api/order/detail/${order_id}`,
  updateCustomer: () => baseUrl + 'api/customer/update',
};
export default API;
